### ISSUE TITLE
JCasC tests don't work with the existing maven test goal

### ISSUE THREAD

**Issue by v1v** [cyrille-leclerc/opentelemetry-plugin#16]
Command: `./mvnw test`

Stacktrace:
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.16 s <<< FAILURE! - in io.jenkins.plugins.opentelemetry.JenkinsOtelPluginIntegrationTest
[ERROR] io.jenkins.plugins.opentelemetry.JenkinsOtelPluginIntegrationTest  Time elapsed: 2.138 s  <<< FAILURE!
java.lang.AssertionError: Unexpected exception 
	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:50)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:595)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:821)
Caused by: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:695)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:753)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:738)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:614)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:583)
	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:47)
	... 5 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.model.GlobalConfigurationCategory$Unclassified : openTelemetry.
Available attributes : administrativeMonitorsConfiguration, artifactManager, buildDiscarders, casCGlobalConfig, defaultFolderConfiguration, defaultView, gitSCM, globalDefaultFlowDurabilityLevel, globalLibraries, junitTestResultStorage, location, mailer, masterBuild, myView, nodeProperties, plugin, pollSCM, projectNamingStrategy, quietPeriod, resourceRoot, scmRetryCount, shell, usageStatistics, viewsTabBar
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:376)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:365)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:753)
	at io.jenkins.plugins.casc.ConfigurationAsCode$$Lambda$195/0000000000000000.apply(Unknown Source)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:689)
	... 10 more
```

Though it works with the IDE:

![image](https://user-images.githubusercontent.com/2871786/108123962-88f78a80-709e-11eb-9764-182cd5714189.png)

**Comment by v1v** [comment]
Interestingly If I run `./mvnw -Dmaven.surefire.debug -Dtest=ConfigurationAsCodeTest test` in my terminal and add a remote configuration in my IDE it works too:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Listening for transport dt_socket at address: 5005
[INFO] Running io.jenkins.plugins.opentelemetry.jcasc.ConfigurationAsCodeTest
Test timeout disabled.
=== Starting io.jenkins.plugins.opentelemetry.jcasc.ConfigurationAsCodeTest
   0.885 [id=1]	INFO	o.jvnet.hudson.test.WarExploder#explode: Picking up existing exploded jenkins.war at /Users/vmartinez/work/src/github.com/v1v/opentelemetry-plugin/target/jenkins-for-test
   1.911 [id=1]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:50295/jenkins/
  47.102 [id=46]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
  49.213 [id=62]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /Users/vmartinez/work/src/github.com/v1v/opentelemetry-plugin/target/tmp/jenkins7483791040424120502/plugins/jdk-tool.jpi
  49.417 [id=62]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /Users/vmartinez/work/src/github.com/v1v/opentelemetry-plugin/target/tmp/jenkins7483791040424120502/plugins/command-launcher.jpi
  54.240 [id=49]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /Users/vmartinez/work/src/github.com/v1v/opentelemetry-plugin/target/tmp/jenkins7483791040424120502/plugins/bouncycastle-api.jpi
  54.808 [id=45]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
  56.335 [id=48]	INFO	j.b.a.SecurityProviderInitializer#addSecurityProvider: Initializing Bouncy Castle security provider.
  58.241 [id=48]	INFO	j.b.a.SecurityProviderInitializer#addSecurityProvider: Bouncy Castle security provider initialized.
  80.805 [id=63]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
  80.840 [id=63]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
 134.459 [id=59]	INFO	i.j.p.o.o.r.JenkinsResource#getAttributes: Attributes: {jenkins.url="#undefined#", service.name="jenkins"}
 134.505 [id=59]	INFO	i.j.p.o.o.r.JenkinsResource#getAttributes: Attributes: {jenkins.url="#undefined#", service.name="jenkins"}
 134.535 [id=59]	INFO	i.j.p.o.OpenTelemetrySdkProvider#initializeNoOp: OpenTelemetry initialized as NoOp
 134.604 [id=63]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
 134.664 [id=47]	INFO	i.j.p.o.c.MonitoringComputerListener#postConstruct: Resources for master computer hudson.model.Hudson$MasterComputer@d555948: OpenTelemetryAttributesAction{attributes=jenkins.computer.name-STRING - #master#, host.name-STRING - my-maC.local, host.ip-STRING - 127.0.0.1}
 134.678 [id=62]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
 134.998 [id=44]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
 134.999 [id=59]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
 135.000 [id=65]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
 135.174 [id=55]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
 204.876 [id=1]	INFO	jenkins.model.Jenkins#cleanUp: Stopping Jenkins
 206.189 [id=1]	INFO	jenkins.model.Jenkins#cleanUp: Jenkins stopped
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 209.483 s - in io.jenkins.plugins.opentelemetry.jcasc.ConfigurationAsCodeTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.19:check (check) @ opentelemetry ---
[INFO] Resolved signature org.codehaus.mojo.signature:java18 version as 1.0 from dependencyManagement
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:50 min
[INFO] Finished at: 2021-02-16T22:21:35Z
[INFO] ------------------------------------------------------------------------
```

**Comment by v1v** [comment]
I managed to find what's causing one of the issues:

```

   0.714 [id=120]	WARNING	h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration, annotation=[none]]; skipping this component
java.lang.Throwable
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:90)
Caused: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must becalled only once before any calls to GlobalOpenTelemetry.get. If you are usingthe OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobalinstead. Previous invocation set to cause of this exception.
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:82)
	at io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider.initializeNoOp(OpenTelemetrySdkProvider.java:101)
	at io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry(JenkinsOpenTelemetryPluginConfiguration.java:83)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:596)
Caused: java.lang.RuntimeException: @PostConstruct public void io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry()
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:598)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error notifying ProvisionListener hudson.ExtensionFinder$GuiceFinder$SezpozModule of io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.
 Reason: java.lang.RuntimeException: @PostConstruct public void io.jenkins.plugins.opentelemetry.JenkinsOpenTelemetryPluginConfiguration.initializeOpenTelemetry()

1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:440)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:402)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:393)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:346)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at jenkins.model.Jenkins.getDescriptorByType(Jenkins.java:1608)
	at hudson.plugins.git.GitSCM.onLoaded(GitSCM.java:2075)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)
```

**Comment by v1v** [comment]
```
./mvnw -Dtest=ConfigurationAsCodeTest test

```

**Comment by cyrille-leclerc** [comment]
Great, easy to fix, Otel exposes `io.opentelemetry.api.GlobalOpenTelemetry#resetForTest()` , we have to find where to add it. I already use it in `io.jenkins.plugins.opentelemetry.OpenTelemetrySdkProvider#initializeForTesting()`

**Comment by cyrille-leclerc** [comment]
Fixed by https://github.com/cyrille-leclerc/opentelemetry-plugin/commit/3d330859084a8c3c0017c8b23798ce18750558f1
